### ISSUE TITLE
about res part

### ISSUE THREAD

**Issue by Yiozolm** [BYchao100/Deep-Lossy-Plus-Residual-Coding#3]
I tried to analyse the res part, and transform the x_lossy into png photo, but I got a black picture.
![1](https://github.com/BYchao100/Deep-Lossy-Plus-Residual-Coding/assets/59084547/587bc0a7-a61e-4191-a999-1372e21e5af3)
After read the whole code, I realized that something maybe went wrong here.(LossyCompressor.decompress in ll_model_eval.py)
![3](https://github.com/BYchao100/Deep-Lossy-Plus-Residual-Coding/assets/59084547/ba169c05-6f80-44c7-9abb-2e1b61ec99cf)
 Before torch.floor, all elements in tensor x_hat were negetive, then we got a zero tensor
I wonder if it's possible to use 'x_hat = torch.ceil(torch.abs(x_hat)).clamp_(min=0, max=255)'
 we can got this
![2](https://github.com/BYchao100/Deep-Lossy-Plus-Residual-Coding/assets/59084547/ff29b61b-f42a-4d48-b5b0-b250aa196d0e)

**Comment by BYchao100** [comment]
DLPR learns lossy reconstruction according to different lambda's. When lambda=0, DLPR_ll learns to set lossy reconstruction to zeros. The LIC becomes a special feature compressor extracting feature u for lossless image compression. This special case of DLPR coding with lambda = 0 is similar to PixelVAE. When lambda>0, DLPR_nll learns high-quality lossy reconstruction.

Please refer to our paper for more details.

https://ieeexplore.ieee.org/abstract/document/10378746

**Comment by BYchao100** [comment]
> I tried to analyse the res part, and transform the x_lossy into png photo, but I got a black picture...

DLPR learns lossy reconstruction according to different lambda's. When lambda=0, DLPR_ll learns to set lossy reconstruction to zeros. The LIC becomes a special feature compressor extracting feature u for lossless image compression. This special case of DLPR coding with lambda = 0 is similar to PixelVAE. When lambda>0, DLPR_nll learns high-quality lossy reconstruction.

Please refer to our paper for more details.

https://ieeexplore.ieee.org/abstract/document/10378746
