### ISSUE TITLE
About the forward in LosslessCompressor

### ISSUE THREAD

**Issue by chunbaobao** [BYchao100/Deep-Lossy-Plus-Residual-Coding#7]
Hi, it is an excellent work! I'm wondering why the `res` variable is multiplied by 2 at this point in the code? Did I miss any details in the paper regarding this part?
https://github.com/BYchao100/Deep-Lossy-Plus-Residual-Coding/blob/027edbb85fc0046a0335faab2d41fb7a37ffbebf/DLPR_ll/ll_model.py#L242

**Comment by BYchao100** [comment]
With this code, we normalize `res` to [-1, 1] and then feed `res_n` to DNN to compute the pdf.

**Comment by chunbaobao** [comment]
thanks for your reply, But the problem remains... I am aware that dividing 255 is to normalize `res`, but whats the point of mutiplying 2 in the end.

**Comment by BYchao100** [comment]
Execuse me. With this code, we normalize `res` to [-2, 2] and then feed `res_n` to DNN to compute the pdf.

**Comment by chunbaobao** [comment]
thanks, it helps a lot! closing issue.
